name: Tests

on: [push, pull_request]

jobs:
  crate-publish:
    name: Crate Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish
        run: cargo check
